# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a480ea1f46221d5628db93b442d42e1ceb077ae37195eac4c4ed17f5319e4b8df597874d98b8b75a72eb487a9f813c09e815c9376aa588c9c2ebd69237897059

test:
  secret_key_base: a78dbb99fb8deb5587fe9cafcf15687acc7069ef3dd0210d19fa1a9ebc515c5ab8c187bc203c374dd9cda91e1b1ef1751f56874cc3348d82f1feb43ea0654411

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
